/**
 * Semantic Color Tokens
 *
 * Context-based color tokens for light and dark modes.
 * Categories: bg (background), text, border, icon
 */

export interface SemanticColorTokens {
  bg: {
    default: string;
    secondary: string;
    tertiary: string;
    hover: string;
    selected: string;
    disabled: string;
    inverse: string;
    brand: string;
    'brand-hover': string;
    'brand-secondary': string;
    'brand-tertiary': string;
    design: string;
    figjam: string;
    'figjam-hover': string;
    'figjam-secondary': string;
    'figjam-tertiary': string;
    component: string;
    assistive: string;
    'assistive-hover': string;
    'assistive-secondary': string;
    'assistive-tertiary': string;
    danger: string;
    'danger-hover': string;
    'danger-secondary': string;
    'danger-tertiary': string;
    warning: string;
    'warning-hover': string;
    'warning-secondary': string;
    'warning-tertiary': string;
    success: string;
    'success-hover': string;
    'success-secondary': string;
    'success-tertiary': string;
    info: string;
    toolbar: string;
    'toolbar-hover': string;
    'toolbar-selected': string;
    menu: string;
    'menu-hover': string;
    'menu-selected': string;
    tooltip: string;
    'tooltip-hover': string;
    'tooltip-selected': string;
  };
  text: {
    default: string;
    secondary: string;
    tertiary: string;
    disabled: string;
    brand: string;
    figjam: string;
    assistive: string;
    danger: string;
    warning: string;
    success: string;
    onbrand: string;
    'onbrand-secondary': string;
    'onbrand-tertiary': string;
    ondisabled: string;
    ondanger: string;
    onwarning: string;
    onsuccess: string;
    onassistive: string;
    onfigjam: string;
    onlightcanvas: string;
    ondarkcanvas: string;
    toolbar: string;
  };
  border: {
    default: string;
    selected: string;
    'selected-strong': string;
    toolbar: string;
    'toolbar-strong': string;
    menu: string;
    'menu-strong': string;
  };
  icon: {
    default: string;
    secondary: string;
    tertiary: string;
    disabled: string;
    brand: string;
    figjam: string;
    danger: string;
    warning: string;
    success: string;
    assistive: string;
    onbrand: string;
    onlightcanvas: string;
    ondarkcanvas: string;
  };
}

export const semanticColors: { light: SemanticColorTokens; dark: SemanticColorTokens } = {
  light: {
    bg: {
      default: '#ffffff',
      secondary: '#f5f5f5',
      tertiary: '#e6e6e6',
      hover: '#f5f5f5',
      selected: '#e5f4ff',
      disabled: '#d9d9d9',
      inverse: '#2c2c2c',
      brand: '#0d99ff',
      'brand-hover': '#007be5',
      'brand-secondary': '#0768cf',
      'brand-tertiary': '#e5f4ff',
      design: '#0d99ff',
      figjam: '#9747ff',
      'figjam-hover': '#8638e5',
      'figjam-secondary': '#7c2bda',
      'figjam-tertiary': '#f1e5ff',
      component: '#9747ff',
      assistive: '#ff24bd',
      'assistive-hover': '#ea10ac',
      'assistive-secondary': '#cb0b96',
      'assistive-tertiary': '#ffe0fc',
      danger: '#f24822',
      'danger-hover': '#dc3412',
      'danger-secondary': '#bd2915',
      'danger-tertiary': '#ffe2e0',
      warning: '#ffcd29',
      'warning-hover': '#ffc21a',
      'warning-secondary': '#fab815',
      'warning-tertiary': '#fff1c2',
      success: '#14ae5c',
      'success-hover': '#009951',
      'success-secondary': '#008043',
      'success-tertiary': '#cff7d3',
      info: '#e5f4ff',
      toolbar: '#2c2c2c',
      'toolbar-hover': '#111111',
      'toolbar-selected': '#0d99ff',
      menu: '#1e1e1e',
      'menu-hover': '#2c2c2c',
      'menu-selected': '#0d99ff',
      tooltip: '#1e1e1e',
      'tooltip-hover': '#2c2c2c',
      'tooltip-selected': '#0d99ff',
    },
    text: {
      default: '#000000e5',
      secondary: '#00000080',
      tertiary: '#0000004d',
      disabled: '#0000004d',
      brand: '#007be5',
      figjam: '#8638e5',
      assistive: '#ea10ac',
      danger: '#dc3412',
      warning: '#b86200',
      success: '#009951',
      onbrand: '#ffffff',
      'onbrand-secondary': '#ffffffcc',
      'onbrand-tertiary': '#ffffff66',
      ondisabled: '#ffffff',
      ondanger: '#ffffff',
      onwarning: '#000000e5',
      onsuccess: '#ffffff',
      onassistive: '#ffffff',
      onfigjam: '#ffffff',
      onlightcanvas: '#000000e5',
      ondarkcanvas: '#ffffffe5',
      toolbar: '#ffffff',
    },
    border: {
      default: '#e6e6e6',
      selected: '#0d99ff',
      'selected-strong': '#007be5',
      toolbar: '#444444',
      'toolbar-strong': '#ffffff',
      menu: '#383838',
      'menu-strong': '#ffffff',
    },
    icon: {
      default: '#000000e5',
      secondary: '#00000080',
      tertiary: '#0000004d',
      disabled: '#0000004d',
      brand: '#007be5',
      figjam: '#8638e5',
      danger: '#f24822',
      warning: '#ffcd29',
      success: '#14ae5c',
      assistive: '#ea10ac',
      onbrand: '#ffffff',
      onlightcanvas: '#000000e5',
      ondarkcanvas: '#ffffffe5',
    },
  },
  dark: {
    bg: {
      default: '#2c2c2c',
      secondary: '#383838',
      tertiary: '#444444',
      hover: '#383838',
      selected: '#0768cf',
      disabled: '#757575',
      inverse: '#ffffff',
      brand: '#0d99ff',
      'brand-hover': '#007be5',
      'brand-secondary': '#0768cf',
      'brand-tertiary': '#034ac1',
      design: '#0d99ff',
      figjam: '#9747ff',
      'figjam-hover': '#8638e5',
      'figjam-secondary': '#7c2bda',
      'figjam-tertiary': '#681abb',
      component: '#9747ff',
      assistive: '#ff24bd',
      'assistive-hover': '#ea10ac',
      'assistive-secondary': '#cb0b96',
      'assistive-tertiary': '#68275e',
      danger: '#f24822',
      'danger-hover': '#dc3412',
      'danger-secondary': '#bd2915',
      'danger-tertiary': '#9f1f18',
      warning: '#ffcd29',
      'warning-hover': '#ffc21a',
      'warning-secondary': '#fab815',
      'warning-tertiary': '#eba611',
      success: '#14ae5c',
      'success-hover': '#009951',
      'success-secondary': '#008043',
      'success-tertiary': '#036838',
      info: '#0768cf',
      toolbar: '#2c2c2c',
      'toolbar-hover': '#111111',
      'toolbar-selected': '#0d99ff',
      menu: '#1e1e1e',
      'menu-hover': '#2c2c2c',
      'menu-selected': '#0d99ff',
      tooltip: '#1e1e1e',
      'tooltip-hover': '#2c2c2c',
      'tooltip-selected': '#0d99ff',
    },
    text: {
      default: '#ffffffe5',
      secondary: '#ffffff',
      tertiary: '#ffffffcc',
      disabled: '#ffffffcc',
      brand: '#80caff',
      figjam: '#d9b8ff',
      assistive: '#fc9ce0',
      danger: '#ffafa3',
      warning: '#ffd966',
      success: '#85e0a3',
      onbrand: '#ffffff',
      'onbrand-secondary': '#ffffffcc',
      'onbrand-tertiary': '#ffffff66',
      ondisabled: '#ffffff',
      ondanger: '#ffffff',
      onwarning: '#000000e5',
      onsuccess: '#ffffff',
      onassistive: '#ffffff',
      onfigjam: '#ffffff',
      onlightcanvas: '#000000e5',
      ondarkcanvas: '#ffffffe5',
      toolbar: '#ffffff',
    },
    border: {
      default: '#444444',
      selected: '#0d99ff',
      'selected-strong': '#007be5',
      toolbar: '#444444',
      'toolbar-strong': '#ffffff',
      menu: '#383838',
      'menu-strong': '#ffffff',
    },
    icon: {
      default: '#ffffffe5',
      secondary: '#ffffffcc',
      tertiary: '#ffffff66',
      disabled: '#ffffffcc',
      brand: '#80caff',
      figjam: '#d9b8ff',
      danger: '#ffafa3',
      warning: '#ffd966',
      success: '#85e0a3',
      assistive: '#fc9ce0',
      onbrand: '#ffffff',
      onlightcanvas: '#000000e5',
      ondarkcanvas: '#ffffffe5',
    },
  },
};
